preload = ~/.config/wallpapers/wall0.jpg
preload = ~/.config/wallpapers/wall1.jpg

wallpaper {
  monitor = DP-4
  path = ~/.config/wallpapers/wall0.jpg
} 

wallpaper {
  monitor = DP-3
  path = ~/.config/wallpapers/wall1.jpg
}
