hl.on("hyprland.start", function()
  hl.exec_cmd("awww-daemon")
  hl.exec_cmd("awww restore")
  hl.exec_cmd("gentoo-pipewire-launcher")
  hl.exec_cmd("/usr/libexec/hyprpolkitagent")
  hl.exec_cmd("dunst")
  hl.exec_cmd("killall -q waybar; sleep .5 && env LC_TIME=de_DE.UTF-8 waybar")
  hl.exec_cmd("hypridle")
  hl.exec_cmd("kanata --cfg ~/.config/kanata/adv360.kbd --no-wait")
end)
