hl.on("hyprland.start", function()
  hl.exec_cmd("awww-daemon")
  hl.exec_cmd("awww restore")
  -- hl.exec_cmd("awww img ~/.wallpaper/cat.gif -o " .. SECONDARY_DISPLAY)
  -- hl.exec_cmd("awww img ~/.wallpaper/train_station.gif -o " .. MAIN_DISPLAY)
  hl.exec_cmd("gentoo-pipewire-launcher")
  hl.exec_cmd("/usr/libexec/hyprpolkitagent")
  hl.exec_cmd("dunst")
  hl.exec_cmd("killall -q waybar; sleep .5 && env LC_TIME=de_DE.UTF-8 waybar")
end)
