# windowrule = suppress_event maximize, class:.* # You'll probably like this.

# Workspace rules
workspace=1,monitor:DP-4,default:true,persistent:true
workspace=2,monitor:DP-4,persistent:true
workspace=3,monitor:DP-4,persistent:true
workspace=4,monitor:DP-4,persistent:true
workspace=5,monitor:DP-4,persistent:true

workspace=6,monitor:DP-3,default:true,persistent:true
workspace=7,monitor:DP-3,persistent:true
workspace=8,monitor:DP-3,persistent:true
workspace=9,monitor:DP-3,persistent:true
workspace=10,monitor:DP-3,persistent:true

# Other
windowrule = stay_focused on, match:class swappy
windowrule = allows_input on, match:class discord
windowrule = monitor DP-3, match:class discord

windowrule {
  name = steam

  match:class = steam

  monitor = DP-3
  workspace = 7 silent
  no_initial_focus = on

  focus_on_activate = off
  suppress_event = activatefocus
}

windowrule = no_focus on, no_initial_focus on, match:class ^(steam)$, match:title ^(notificationtoasts_*)$

windowrule = float on, match:class ^(jetbrains-.*)$, match:title ^(win[0-9]+)$
windowrule = no_focus on, match:class ^(jetbrains-.*)$, match:title ^(win[0-9]+)$
