[font]
# normal={family = "Hack Nerd Font Mono", style = "Regular"}
normal={family = "Hack", style = "Regular"}

[window]
opacity=0.7
blur=true

[keyboard]
bindings = [{ key = "V", mods = "Control", action = "Paste"}]

# [colors.primary]
# foreground = "#000000"
