import = [
 "catppuccin-machhiato.toml"
 ]

[font]
# normal={family = "Hack Nerd Font Mono", style = "Regular"}
normal={family = "Hack", style = "Regular"}

[window]
opacity=0.7
blur=true

[keyboard]
bindings = [{ key = "V", mods = "Control", action = "Paste"}]



# [colors.primary]
# background = '0x161616'
# foreground = '0xf2f4f8'
#
# # Colors the cursor will use if `custom_cursor_colors` is true
# [colors.cursor]
# text = '0x161616'
# cursor = '0xf2f4f8'
#
# # Normal colors
# [colors.normal]
# black = '0x161616'
# red = '0x3ddbd9'
# green = '0x33b1ff'
# yellow = '0xee5396'
# blue = '0x42be65'
# magenta = '0xbe95ff'
# cyan = '0xff7eb6'
# white = '0xf2f4f8'
#
# # Bright colors
# [colors.bright]
# black = '0x525252'
# red = '0x3ddbd9'
# green = '0x33b1ff'
# yellow = '0xee5396'
# blue = '0x42be65'
# magenta = '0xbe95ff'
# cyan = '0xff7eb6'
# white = '0x08bdba'
#
# [[colors.indexed_colors]]
# index = 16
# color = "0x78a9ff"
#
# [[colors.indexed_colors]]
# index = 17
# color = "0x82cfff"
#
# [[colors.indexed_colors]]
# index = 18
# color = "0x262626"
#
# [[colors.indexed_colors]]
# index = 19
# color = "0x393939"
#
# [[colors.indexed_colors]]
# index = 20
# color = "0xdde1e6"
#
# [[colors.indexed_colors]]
# index = 21
# color = "0xffffff"
# # [colors.primary]
# foreground = "#000000"
