# windowrule = suppress_event maximize, class:.* # You'll probably like this.

# Workspace rules
workspace=1,monitor:DP-4,default:true,persistent:true
workspace=2,monitor:DP-4,persistent:true
workspace=3,monitor:DP-4,persistent:true
workspace=4,monitor:DP-4,persistent:true
workspace=5,monitor:DP-4,persistent:true

# workspace=6,monitor:DP-2,default:true,persistent:true
# workspace=7,monitor:DP-2,persistent:true
# workspace=8,monitor:DP-2,persistent:true
# workspace=9,monitor:DP-2,persistent:true
# workspace=10,monitor:DP-2,persistent:true

workspace=6,monitor:DP-3,default:true,persistent:true
workspace=7,monitor:DP-3,persistent:true
workspace=8,monitor:DP-3,persistent:true
workspace=9,monitor:DP-3,persistent:true
workspace=10,monitor:DP-3,persistent:true

# Other
windowrule = stay_focused on, match:class swappy
windowrule = allows_input on, match:class discord
windowrule = monitor DP-2, match:class discord
windowrule = no_initial_focus on, match:initial_class steam
windowrule = monitor DP-2, match:initial_class steam

windowrule = float on, match:class ^(jetbrains-.*)$, match:title ^(win[0-9]+)$
windowrule = no_focus on, match:class ^(jetbrains-.*)$, match:title ^(win[0-9]+)$
